version: '3.2'
services:
  db:
    image: voidzster/postgrespro-1c
    restart: always
    ports:
      - "5432:5432"
    volumes: 
     - ./DATA/pgdata:/data
     - ./BACKUPS:/tmp/backups
     - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_PASSWORD: password123

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@mail.com
      - PGADMIN_DEFAULT_PASSWORD=password123
    links: 
      - db


